apiVersion: v1
kind: Service

metadata:
  name: app-service
  labels:
    app: app

spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-deployment

spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: alexandroandrademartinez/practice-java-spring-mongo-k8s:0.0.1-SNAPSHOT
        env:
          - name: MONGO_HOST
            value: mongo
        ports:
          - containerPort: 8080
