apiVersion: v1
kind: Service

metadata:
  name: mongo-express-service
  labels:
    app: mongo-express

spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongo-express-deployment

spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:0.54
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo
          ports:
            - containerPort: 8081